/**
 * AWS Transcribe Streaming Client
 *
 * Handles the WebSocket connection and event-stream encoding/decoding
 * for real-time speech-to-text using AWS Transcribe Streaming.
 *
 * This client connects directly to AWS Transcribe from the browser,
 * using a pre-signed WebSocket URL generated by the server.
 */

import type {
  STTStreamingSession,
  STTStreamingSessionFactory,
} from '@/packages/survey-form-package/src/renderer/layouts/VoiceLayout/types';

/**
 * Configuration for creating an STT session
 */
interface AWSTranscribeConfig {
  /** API endpoint to get pre-signed WebSocket URL */
  websocketUrlEndpoint?: string;
  /** Language code (e.g., 'en-US') */
  language?: string;
  /** Audio sample rate in Hz */
  sampleRate?: number;
}

/**
 * Extended STT session with prewarm support
 */
interface STTStreamingSessionWithPrewarm extends STTStreamingSession {
  /** Pre-warm the session by fetching the WebSocket URL early */
  prewarm: () => Promise<void>;
}

/**
 * Extended factory that returns sessions with prewarm support
 */
type STTStreamingSessionFactoryWithPrewarm = (
  onTranscript: (transcript: string, isFinal: boolean) => void,
  onError?: (error: string) => void,
  config?: { language?: string; sampleRate?: number }
) => STTStreamingSessionWithPrewarm;

/**
 * Event-stream message structure for AWS Transcribe
 */
interface EventStreamMessage {
  headers: Record<string, { type: string; value: string | number }>;
  body: Uint8Array;
}

/**
 * Encode a message in AWS event-stream format
 * See: https://docs.aws.amazon.com/transcribe/latest/dg/streaming-format.html
 */
function encodeEventStreamMessage(audioChunk: ArrayBuffer): Uint8Array {
  const audioData = new Uint8Array(audioChunk);

  // Headers for audio event
  const headers: Array<{ name: string; type: number; value: string }> = [
    { name: ':content-type', type: 7, value: 'application/octet-stream' },
    { name: ':event-type', type: 7, value: 'AudioEvent' },
    { name: ':message-type', type: 7, value: 'event' },
  ];

  // Calculate headers length
  let headersLength = 0;
  for (const header of headers) {
    headersLength += 1 + header.name.length; // name length byte + name
    headersLength += 1; // type byte
    headersLength += 2 + header.value.length; // value length (2 bytes) + value
  }

  // Message structure:
  // - Total byte length (4 bytes, big-endian)
  // - Headers byte length (4 bytes, big-endian)
  // - Prelude CRC (4 bytes)
  // - Headers
  // - Payload
  // - Message CRC (4 bytes)

  const totalLength = 4 + 4 + 4 + headersLength + audioData.length + 4;
  const message = new Uint8Array(totalLength);
  const view = new DataView(message.buffer);

  let offset = 0;

  // Total byte length
  view.setUint32(offset, totalLength, false);
  offset += 4;

  // Headers byte length
  view.setUint32(offset, headersLength, false);
  offset += 4;

  // Prelude CRC (simplified - AWS SDK handles this properly)
  const preludeCrc = crc32(message.slice(0, 8));
  view.setUint32(offset, preludeCrc, false);
  offset += 4;

  // Write headers
  for (const header of headers) {
    // Header name length (1 byte)
    message[offset++] = header.name.length;
    // Header name
    for (let i = 0; i < header.name.length; i++) {
      message[offset++] = header.name.charCodeAt(i);
    }
    // Header type (7 = string)
    message[offset++] = header.type;
    // Header value length (2 bytes, big-endian)
    view.setUint16(offset, header.value.length, false);
    offset += 2;
    // Header value
    for (let i = 0; i < header.value.length; i++) {
      message[offset++] = header.value.charCodeAt(i);
    }
  }

  // Write payload (audio data)
  message.set(audioData, offset);
  offset += audioData.length;

  // Message CRC
  const messageCrc = crc32(message.slice(0, offset));
  view.setUint32(offset, messageCrc, false);

  return message;
}

/**
 * Decode an AWS event-stream message
 */
function decodeEventStreamMessage(data: ArrayBuffer): {
  messageType: string;
  eventType?: string;
  transcript?: string;
  isPartial?: boolean;
  error?: string;
} | null {
  try {
    const view = new DataView(data);
    const bytes = new Uint8Array(data);

    // Read total length and headers length
    const totalLength = view.getUint32(0, false);
    const headersLength = view.getUint32(4, false);

    // Skip prelude (8 bytes) and prelude CRC (4 bytes)
    let offset = 12;

    // Parse headers
    const headers: Record<string, string> = {};
    const headersEnd = offset + headersLength;

    while (offset < headersEnd) {
      // Header name length
      const nameLength = bytes[offset++];
      // Header name
      const name = String.fromCharCode(...bytes.slice(offset, offset + nameLength));
      offset += nameLength;
      // Header type
      const type = bytes[offset++];
      // Header value
      if (type === 7) {
        // String type
        const valueLength = view.getUint16(offset, false);
        offset += 2;
        const value = String.fromCharCode(...bytes.slice(offset, offset + valueLength));
        offset += valueLength;
        headers[name] = value;
      } else {
        // Skip unknown types
        break;
      }
    }

    const messageType = headers[':message-type'];
    const eventType = headers[':event-type'];

    if (messageType === 'exception' || messageType === 'error') {
      // Error message - try to parse the body
      const payloadStart = 12 + headersLength;
      const payloadEnd = totalLength - 4; // Exclude message CRC
      const payload = bytes.slice(payloadStart, payloadEnd);
      const errorText = new TextDecoder().decode(payload);
      return { messageType, error: errorText };
    }

    if (messageType === 'event' && eventType === 'TranscriptEvent') {
      // Parse the JSON payload
      const payloadStart = 12 + headersLength;
      const payloadEnd = totalLength - 4; // Exclude message CRC
      const payload = bytes.slice(payloadStart, payloadEnd);
      const jsonStr = new TextDecoder().decode(payload);

      try {
        const transcriptEvent = JSON.parse(jsonStr);
        const results = transcriptEvent?.Transcript?.Results || [];

        if (results.length > 0) {
          const result = results[0];
          const alternatives = result.Alternatives || [];
          if (alternatives.length > 0) {
            return {
              messageType,
              eventType,
              transcript: alternatives[0].Transcript || '',
              isPartial: result.IsPartial,
            };
          }
        }
      } catch (e) {
        console.error('Failed to parse transcript JSON:', e);
      }
    }

    return { messageType, eventType };
  } catch (error) {
    console.error('Failed to decode event-stream message:', error);
    return null;
  }
}

/**
 * Simple CRC32 implementation for event-stream
 */
function crc32(data: Uint8Array): number {
  let crc = 0xffffffff;
  const table = getCrc32Table();

  for (let i = 0; i < data.length; i++) {
    crc = (crc >>> 8) ^ table[(crc ^ data[i]) & 0xff];
  }

  return (crc ^ 0xffffffff) >>> 0;
}

let crc32Table: Uint32Array | null = null;

function getCrc32Table(): Uint32Array {
  if (crc32Table) return crc32Table;

  crc32Table = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let j = 0; j < 8; j++) {
      c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }
    crc32Table[i] = c;
  }
  return crc32Table;
}

/**
 * Create an AWS Transcribe streaming session
 */
function createAWSTranscribeSession(
  websocketUrl: string,
  onTranscript: (transcript: string, isFinal: boolean) => void,
  onError?: (error: string) => void
): STTStreamingSession {
  let ws: WebSocket | null = null;
  let isActive = false;
  let audioQueue: ArrayBuffer[] = [];
  let isConnected = false;

  const session: STTStreamingSession = {
    get isActive() {
      return isActive;
    },

    async start() {
      if (isActive) return;

      return new Promise<void>((resolve, reject) => {
        try {
          ws = new WebSocket(websocketUrl);
          ws.binaryType = 'arraybuffer';

          const connectionTimeout = setTimeout(() => {
            if (!isConnected) {
              ws?.close();
              reject(new Error('WebSocket connection timeout'));
            }
          }, 10000);

          ws.onopen = () => {
            clearTimeout(connectionTimeout);
            isActive = true;
            isConnected = true;

            // Send any queued audio
            while (audioQueue.length > 0) {
              const audio = audioQueue.shift();
              if (audio) {
                session.sendAudio(audio);
              }
            }

            resolve();
          };

          ws.onmessage = (event) => {
            if (event.data instanceof ArrayBuffer) {
              const decoded = decodeEventStreamMessage(event.data);
              if (decoded) {
                if (decoded.error) {
                  console.error('AWS Transcribe error:', decoded.error);
                  onError?.(decoded.error);
                } else if (decoded.transcript !== undefined) {
                  onTranscript(decoded.transcript, !decoded.isPartial);
                }
              }
            }
          };

          ws.onerror = (event) => {
            console.error('WebSocket error:', event);
            onError?.('WebSocket connection error');
          };

          ws.onclose = (event) => {
            isActive = false;
            isConnected = false;
            if (event.code !== 1000 && event.code !== 1005) {
              console.warn('WebSocket closed:', event.code, event.reason);
            }
          };
        } catch (error) {
          reject(error);
        }
      });
    },

    sendAudio(audio: ArrayBuffer) {
      if (!isConnected || !ws || ws.readyState !== WebSocket.OPEN) {
        // Queue audio if not connected yet
        if (isActive) {
          audioQueue.push(audio);
        }
        return;
      }

      try {
        const encodedMessage = encodeEventStreamMessage(audio);
        ws.send(encodedMessage);
      } catch (error) {
        console.error('Failed to send audio:', error);
      }
    },

    async end() {
      if (!isActive) return;

      isActive = false;
      audioQueue = [];

      if (ws && ws.readyState === WebSocket.OPEN) {
        // Send empty audio event to signal end of stream
        try {
          const emptyMessage = encodeEventStreamMessage(new ArrayBuffer(0));
          ws.send(emptyMessage);
        } catch (e) {
          // Ignore
        }

        // Close after a short delay to allow final transcripts
        await new Promise((resolve) => setTimeout(resolve, 500));
        ws.close(1000, 'Session ended');
      }

      ws = null;
    },
  };

  return session;
}

/**
 * Cached WebSocket URL with expiration tracking
 */
interface CachedUrl {
  url: string;
  fetchedAt: number;
  expiresIn: number; // seconds
}

/**
 * Create an STT streaming session factory for AWS Transcribe
 *
 * Features:
 * - Pre-warming: Call prewarm() to fetch the WebSocket URL early
 * - URL caching: URLs are cached and reused until they expire
 * - Fast start: If pre-warmed, start() connects immediately without network delay
 *
 * Usage:
 * ```
 * const sttSessionFactory = createAWSTranscribeSessionFactory({
 *   websocketUrlEndpoint: '/api/voice-survey/stt/websocket',
 *   language: 'en-US',
 *   sampleRate: 16000,
 * });
 *
 * // Pre-warm during initialization (optional but recommended)
 * const session = sttSessionFactory(onTranscript, onError);
 * await session.prewarm();
 *
 * // Later, start() will be fast because URL is already cached
 * await session.start();
 *
 * // Pass to VoiceLayout via customData
 * customData={{ sttSessionFactory }}
 * ```
 */
export function createAWSTranscribeSessionFactory(
  config: AWSTranscribeConfig = {}
): STTStreamingSessionFactory {
  const {
    websocketUrlEndpoint = '/api/voice-survey/stt/websocket',
    language: defaultLanguage = 'en-US',
    sampleRate: defaultSampleRate = 16000,
  } = config;

  // Shared URL cache across sessions (URLs are valid for ~5 minutes)
  let cachedUrl: CachedUrl | null = null;
  let fetchPromise: Promise<CachedUrl> | null = null;

  /**
   * Fetch a new WebSocket URL (with deduplication)
   */
  async function fetchWebSocketUrl(language: string, sampleRate: number): Promise<string> {
    // Check if cached URL is still valid (with 30 second buffer)
    if (cachedUrl) {
      const elapsed = (Date.now() - cachedUrl.fetchedAt) / 1000;
      if (elapsed < cachedUrl.expiresIn - 30) {
        return cachedUrl.url;
      }
      cachedUrl = null;
    }

    // If already fetching, wait for that request
    if (fetchPromise) {
      const result = await fetchPromise;
      return result.url;
    }

    // Fetch new URL
    fetchPromise = (async () => {
      const params = new URLSearchParams({
        language,
        sampleRate: sampleRate.toString(),
      });

      const response = await fetch(`${websocketUrlEndpoint}?${params}`);
      const data = await response.json();

      if (!data.success || !data.websocketUrl) {
        throw new Error(data.error || 'Failed to get WebSocket URL');
      }

      const cached: CachedUrl = {
        url: data.websocketUrl,
        fetchedAt: Date.now(),
        expiresIn: data.expiresIn || 300,
      };

      cachedUrl = cached;
      fetchPromise = null;

      return cached;
    })();

    const result = await fetchPromise;
    return result.url;
  }

  return (
    onTranscript: (transcript: string, isFinal: boolean) => void,
    onError?: (error: string) => void,
    sessionConfig?: { language?: string; sampleRate?: number }
  ): STTStreamingSessionWithPrewarm => {
    const language = sessionConfig?.language || defaultLanguage;
    const sampleRate = sessionConfig?.sampleRate || defaultSampleRate;

    let innerSession: STTStreamingSession | null = null;

    const session: STTStreamingSessionWithPrewarm = {
      get isActive() {
        return innerSession?.isActive ?? false;
      },

      /**
       * Pre-warm by fetching the WebSocket URL early.
       * This is optional but reduces latency when start() is called.
       */
      async prewarm() {
        try {
          await fetchWebSocketUrl(language, sampleRate);
        } catch (error) {
          // Prewarm errors are non-fatal - start() will retry
          console.warn('STT prewarm failed (will retry on start):', error);
        }
      },

      async start() {
        try {
          const websocketUrl = await fetchWebSocketUrl(language, sampleRate);
          innerSession = createAWSTranscribeSession(websocketUrl, onTranscript, onError);
          await innerSession.start();
        } catch (error) {
          const errorMsg = error instanceof Error ? error.message : 'Failed to start STT session';
          console.error('STT session start error:', errorMsg);
          onError?.(errorMsg);
          throw error;
        }
      },

      sendAudio(audio: ArrayBuffer) {
        innerSession?.sendAudio(audio);
      },

      async end() {
        await innerSession?.end();
        innerSession = null;
      },
    };

    return session;
  };
}

export type { AWSTranscribeConfig, STTStreamingSession, STTStreamingSessionFactory, STTStreamingSessionWithPrewarm };
