/**
 * AWS Transcribe Streaming Client
 *
 * Handles the WebSocket connection and event-stream encoding/decoding
 * for real-time speech-to-text using AWS Transcribe Streaming.
 *
 * This client connects directly to AWS Transcribe from the browser,
 * using a pre-signed WebSocket URL generated by the server.
 */

import type {
  STTStreamingSession,
  STTStreamingSessionFactory,
} from '@/packages/survey-form-package/src/renderer/layouts/VoiceLayout/types';

/**
 * Configuration for creating an STT session
 */
interface AWSTranscribeConfig {
  /** API endpoint to get pre-signed WebSocket URL */
  websocketUrlEndpoint?: string;
  /** Language code (e.g., 'en-US') */
  language?: string;
  /** Audio sample rate in Hz */
  sampleRate?: number;
  /** Initial connection timeout in ms (default: 5000) - kept short for fast retry */
  initialTimeout?: number;
  /** Connection timeout for retry attempts in ms (default: 10000) */
  retryTimeout?: number;
  /** Max retry attempts on connection failure (default: 3) */
  maxRetries?: number;
  /**
   * Delay in ms to wait after receiving a final transcript before calling callback.
   * This allows users to take natural pauses without triggering submission.
   * If more speech is detected during this delay, the timer resets.
   * @default 1500
   */
  finalTranscriptDelay?: number;
  /** Enable debug logging */
  debug?: boolean;
}

/**
 * Extended STT session with connection management
 */
interface STTStreamingSessionWithPrewarm extends STTStreamingSession {
  /** Pre-warm the session by fetching the WebSocket URL early */
  prewarm: () => Promise<void>;
  /** Pre-connect the WebSocket (call during AI speaking to have connection ready) */
  preconnect: () => Promise<void>;
  /** Whether the WebSocket is currently connected */
  isConnected: boolean;
  /** Pause listening (stops sending audio but keeps connection open) */
  pause: () => void;
  /** Resume listening (starts sending audio again) */
  resume: () => void;
  /** Whether listening is currently paused */
  isPaused: boolean;
}

/**
 * Extended factory that returns sessions with prewarm support
 */
type STTStreamingSessionFactoryWithPrewarm = (
  onTranscript: (transcript: string, isFinal: boolean) => void,
  onError?: (error: string) => void,
  config?: { language?: string; sampleRate?: number }
) => STTStreamingSessionWithPrewarm;

/**
 * Event-stream message structure for AWS Transcribe
 */
interface EventStreamMessage {
  headers: Record<string, { type: string; value: string | number }>;
  body: Uint8Array;
}

/**
 * Encode a message in AWS event-stream format
 * See: https://docs.aws.amazon.com/transcribe/latest/dg/streaming-format.html
 */
function encodeEventStreamMessage(audioChunk: ArrayBuffer): Uint8Array {
  const audioData = new Uint8Array(audioChunk);

  // Headers for audio event
  const headers: Array<{ name: string; type: number; value: string }> = [
    { name: ':content-type', type: 7, value: 'application/octet-stream' },
    { name: ':event-type', type: 7, value: 'AudioEvent' },
    { name: ':message-type', type: 7, value: 'event' },
  ];

  // Calculate headers length
  let headersLength = 0;
  for (const header of headers) {
    headersLength += 1 + header.name.length; // name length byte + name
    headersLength += 1; // type byte
    headersLength += 2 + header.value.length; // value length (2 bytes) + value
  }

  // Message structure:
  // - Total byte length (4 bytes, big-endian)
  // - Headers byte length (4 bytes, big-endian)
  // - Prelude CRC (4 bytes)
  // - Headers
  // - Payload
  // - Message CRC (4 bytes)

  const totalLength = 4 + 4 + 4 + headersLength + audioData.length + 4;
  const message = new Uint8Array(totalLength);
  const view = new DataView(message.buffer);

  let offset = 0;

  // Total byte length
  view.setUint32(offset, totalLength, false);
  offset += 4;

  // Headers byte length
  view.setUint32(offset, headersLength, false);
  offset += 4;

  // Prelude CRC (simplified - AWS SDK handles this properly)
  const preludeCrc = crc32(message.slice(0, 8));
  view.setUint32(offset, preludeCrc, false);
  offset += 4;

  // Write headers
  for (const header of headers) {
    // Header name length (1 byte)
    message[offset++] = header.name.length;
    // Header name
    for (let i = 0; i < header.name.length; i++) {
      message[offset++] = header.name.charCodeAt(i);
    }
    // Header type (7 = string)
    message[offset++] = header.type;
    // Header value length (2 bytes, big-endian)
    view.setUint16(offset, header.value.length, false);
    offset += 2;
    // Header value
    for (let i = 0; i < header.value.length; i++) {
      message[offset++] = header.value.charCodeAt(i);
    }
  }

  // Write payload (audio data)
  message.set(audioData, offset);
  offset += audioData.length;

  // Message CRC
  const messageCrc = crc32(message.slice(0, offset));
  view.setUint32(offset, messageCrc, false);

  return message;
}

/**
 * Decode an AWS event-stream message
 */
function decodeEventStreamMessage(data: ArrayBuffer): {
  messageType: string;
  eventType?: string;
  transcript?: string;
  isPartial?: boolean;
  error?: string;
} | null {
  try {
    const view = new DataView(data);
    const bytes = new Uint8Array(data);

    // Read total length and headers length
    const totalLength = view.getUint32(0, false);
    const headersLength = view.getUint32(4, false);

    // Skip prelude (8 bytes) and prelude CRC (4 bytes)
    let offset = 12;

    // Parse headers
    const headers: Record<string, string> = {};
    const headersEnd = offset + headersLength;

    while (offset < headersEnd) {
      // Header name length
      const nameLength = bytes[offset++];
      // Header name
      const name = String.fromCharCode(...bytes.slice(offset, offset + nameLength));
      offset += nameLength;
      // Header type
      const type = bytes[offset++];
      // Header value
      if (type === 7) {
        // String type
        const valueLength = view.getUint16(offset, false);
        offset += 2;
        const value = String.fromCharCode(...bytes.slice(offset, offset + valueLength));
        offset += valueLength;
        headers[name] = value;
      } else {
        // Skip unknown types
        break;
      }
    }

    const messageType = headers[':message-type'];
    const eventType = headers[':event-type'];

    if (messageType === 'exception' || messageType === 'error') {
      // Error message - try to parse the body
      const payloadStart = 12 + headersLength;
      const payloadEnd = totalLength - 4; // Exclude message CRC
      const payload = bytes.slice(payloadStart, payloadEnd);
      const errorText = new TextDecoder().decode(payload);
      return { messageType, error: errorText };
    }

    if (messageType === 'event' && eventType === 'TranscriptEvent') {
      // Parse the JSON payload
      const payloadStart = 12 + headersLength;
      const payloadEnd = totalLength - 4; // Exclude message CRC
      const payload = bytes.slice(payloadStart, payloadEnd);
      const jsonStr = new TextDecoder().decode(payload);

      try {
        const transcriptEvent = JSON.parse(jsonStr);
        const results = transcriptEvent?.Transcript?.Results || [];

        if (results.length > 0) {
          const result = results[0];
          const alternatives = result.Alternatives || [];
          if (alternatives.length > 0) {
            return {
              messageType,
              eventType,
              transcript: alternatives[0].Transcript || '',
              isPartial: result.IsPartial,
            };
          }
        }
      } catch (e) {
        console.error('Failed to parse transcript JSON:', e);
      }
    }

    return { messageType, eventType };
  } catch (error) {
    console.error('Failed to decode event-stream message:', error);
    return null;
  }
}

/**
 * Simple CRC32 implementation for event-stream
 */
function crc32(data: Uint8Array): number {
  let crc = 0xffffffff;
  const table = getCrc32Table();

  for (let i = 0; i < data.length; i++) {
    crc = (crc >>> 8) ^ table[(crc ^ data[i]) & 0xff];
  }

  return (crc ^ 0xffffffff) >>> 0;
}

let crc32Table: Uint32Array | null = null;

function getCrc32Table(): Uint32Array {
  if (crc32Table) return crc32Table;

  crc32Table = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let j = 0; j < 8; j++) {
      c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }
    crc32Table[i] = c;
  }
  return crc32Table;
}

/**
 * Create an AWS Transcribe streaming session with persistent connection support
 */
function createAWSTranscribeSession(
  websocketUrl: string,
  onTranscript: (transcript: string, isFinal: boolean) => void,
  onError?: (error: string) => void,
  options?: { connectionTimeout?: number; finalTranscriptDelay?: number; debug?: boolean }
): STTStreamingSessionWithPrewarm {
  const { connectionTimeout = 15000, finalTranscriptDelay = 1500, debug = false } = options || {};
  const log = debug ? console.log.bind(console, '[AWSTranscribe]') : () => {};

  let ws: WebSocket | null = null;
  let isActive = false;       // True when actively listening (sending audio)
  let isConnected = false;    // True when WebSocket is connected
  let isPaused = false;       // True when paused (connected but not sending audio)
  let audioQueue: ArrayBuffer[] = [];
  let connectionTimeoutId: ReturnType<typeof setTimeout> | null = null;
  let connectPromise: Promise<void> | null = null;

  // State for transcript finalization delay
  let accumulatedTranscript = '';
  let finalizationTimerId: ReturnType<typeof setTimeout> | null = null;

  /**
   * Clear the finalization timer
   */
  const clearFinalizationTimer = () => {
    if (finalizationTimerId) {
      clearTimeout(finalizationTimerId);
      finalizationTimerId = null;
    }
  };

  /**
   * Handle incoming transcript with finalization delay
   */
  const handleTranscript = (transcript: string, isFinal: boolean) => {
    // Ignore transcripts when paused
    if (isPaused) return;

    if (!isFinal) {
      onTranscript(transcript, false);
      return;
    }

    log('Final transcript received:', transcript);

    if (accumulatedTranscript) {
      accumulatedTranscript += ' ' + transcript;
    } else {
      accumulatedTranscript = transcript;
    }

    // Show accumulated as partial for feedback
    onTranscript(accumulatedTranscript, false);

    // Reset finalization timer
    clearFinalizationTimer();
    finalizationTimerId = setTimeout(() => {
      if (accumulatedTranscript && isActive && !isPaused) {
        log('Finalization delay complete, sending final:', accumulatedTranscript);
        const finalText = accumulatedTranscript;
        accumulatedTranscript = '';
        onTranscript(finalText, true);
      }
    }, finalTranscriptDelay);
  };

  /**
   * Internal connect function
   */
  const connect = (): Promise<void> => {
    if (isConnected) return Promise.resolve();
    if (connectPromise) return connectPromise;

    connectPromise = new Promise<void>((resolve, reject) => {
      let resolved = false;

      const cleanup = () => {
        if (connectionTimeoutId) {
          clearTimeout(connectionTimeoutId);
          connectionTimeoutId = null;
        }
        connectPromise = null;
      };

      const rejectOnce = (error: Error) => {
        if (!resolved) {
          resolved = true;
          cleanup();
          reject(error);
        }
      };

      const resolveOnce = () => {
        if (!resolved) {
          resolved = true;
          cleanup();
          resolve();
        }
      };

      try {
        log('Connecting to WebSocket...');
        ws = new WebSocket(websocketUrl);
        ws.binaryType = 'arraybuffer';

        connectionTimeoutId = setTimeout(() => {
          if (!isConnected && ws) {
            log('Connection timeout');
            ws.close();
            rejectOnce(new Error('WebSocket connection timeout'));
          }
        }, connectionTimeout);

        ws.onopen = () => {
          log('WebSocket connected');
          isConnected = true;

          // Send queued audio
          while (audioQueue.length > 0 && !isPaused) {
            const audio = audioQueue.shift();
            if (audio) session.sendAudio(audio);
          }

          resolveOnce();
        };

        ws.onmessage = (event) => {
          if (event.data instanceof ArrayBuffer) {
            const decoded = decodeEventStreamMessage(event.data);
            if (decoded) {
              if (decoded.error) {
                // Check if this is a timeout error from AWS
                const isTimeoutError = decoded.error.includes('timed out') ||
                                       decoded.error.includes('no new audio');

                if (isTimeoutError) {
                  log('AWS Transcribe session timed out, will reconnect on next start');
                  // Mark as disconnected so next start() will reconnect
                  isConnected = false;
                  isActive = false;
                  isPaused = false;
                  // Close the WebSocket gracefully
                  if (ws && ws.readyState === WebSocket.OPEN) {
                    ws.close(1000, 'Session timed out');
                  }
                  // Don't call onError for timeout - it's expected and we'll reconnect automatically
                } else {
                  console.error('AWS Transcribe error:', decoded.error);
                  onError?.(decoded.error);
                }
              } else if (decoded.transcript !== undefined) {
                handleTranscript(decoded.transcript, !decoded.isPartial);
              }
            }
          }
        };

        ws.onerror = (event) => {
          log('WebSocket error:', event);
        };

        ws.onclose = (event) => {
          log('WebSocket closed:', event.code, event.reason);
          const wasConnected = isConnected;
          isActive = false;
          isConnected = false;
          isPaused = false;

          if (accumulatedTranscript) {
            clearFinalizationTimer();
            onTranscript(accumulatedTranscript, true);
            accumulatedTranscript = '';
          }

          if (!wasConnected) {
            if (event.code === 1006) {
              rejectOnce(new Error('WebSocket connection failed - please check your network'));
            } else {
              rejectOnce(new Error(`WebSocket closed before connecting (code: ${event.code})`));
            }
          } else if (event.code !== 1000 && event.code !== 1005) {
            onError?.(`Connection lost (code: ${event.code})`);
          }
        };
      } catch (error) {
        log('Error creating WebSocket:', error);
        rejectOnce(error instanceof Error ? error : new Error(String(error)));
      }
    });

    return connectPromise;
  };

  const session: STTStreamingSessionWithPrewarm = {
    get isActive() {
      return isActive;
    },

    get isConnected() {
      return isConnected;
    },

    get isPaused() {
      return isPaused;
    },

    async prewarm() {
      // For this session type, prewarm is the same as preconnect
      return this.preconnect();
    },

    async preconnect() {
      log('Pre-connecting WebSocket...');
      await connect();
      isPaused = true;  // Start in paused state
    },

    async start() {
      if (isActive && !isPaused) return;

      // Reset transcript state
      accumulatedTranscript = '';
      clearFinalizationTimer();

      // Connect if not already connected
      await connect();

      isActive = true;
      isPaused = false;
      log('Started listening');
    },

    pause() {
      if (!isActive || isPaused) return;
      log('Pausing (keeping connection open)');
      isPaused = true;

      // Send any accumulated transcript as final
      if (accumulatedTranscript) {
        clearFinalizationTimer();
        onTranscript(accumulatedTranscript, true);
        accumulatedTranscript = '';
      }
    },

    resume() {
      if (!isConnected || !isPaused) return;
      log('Resuming listening');
      isPaused = false;
      isActive = true;
      accumulatedTranscript = '';
      clearFinalizationTimer();
    },

    sendAudio(audio: ArrayBuffer) {
      // Don't send if paused
      if (isPaused) return;

      if (!isConnected || !ws || ws.readyState !== WebSocket.OPEN) {
        if (isActive) {
          audioQueue.push(audio);
        }
        return;
      }

      try {
        const encodedMessage = encodeEventStreamMessage(audio);
        ws.send(encodedMessage);
      } catch (error) {
        console.error('Failed to send audio:', error);
      }
    },

    async end() {
      log('Ending session');
      isActive = false;
      isPaused = false;
      audioQueue = [];

      if (accumulatedTranscript) {
        clearFinalizationTimer();
        onTranscript(accumulatedTranscript, true);
        accumulatedTranscript = '';
      }

      if (ws) {
        if (ws.readyState === WebSocket.OPEN) {
          try {
            const emptyMessage = encodeEventStreamMessage(new ArrayBuffer(0));
            ws.send(emptyMessage);
          } catch (e) {
            // Ignore
          }

          await new Promise((resolve) => setTimeout(resolve, 300));
          ws.close(1000, 'Session ended');
        } else if (ws.readyState === WebSocket.CONNECTING) {
          ws.close();
        }
        ws = null;
      }

      clearFinalizationTimer();
    },
  };

  return session;
}

/**
 * Cached WebSocket URL with expiration tracking
 */
interface CachedUrl {
  url: string;
  fetchedAt: number;
  expiresIn: number; // seconds
}

/**
 * Create an STT streaming session factory for AWS Transcribe
 *
 * Features:
 * - Pre-warming: Call prewarm() to fetch the WebSocket URL early
 * - URL caching: URLs are cached and reused until they expire
 * - Fast start: If pre-warmed, start() connects immediately without network delay
 *
 * Usage:
 * ```
 * const sttSessionFactory = createAWSTranscribeSessionFactory({
 *   websocketUrlEndpoint: '/api/voice-survey/stt/websocket',
 *   language: 'en-US',
 *   sampleRate: 16000,
 * });
 *
 * // Pre-warm during initialization (optional but recommended)
 * const session = sttSessionFactory(onTranscript, onError);
 * await session.prewarm();
 *
 * // Later, start() will be fast because URL is already cached
 * await session.start();
 *
 * // Pass to VoiceLayout via customData
 * customData={{ sttSessionFactory }}
 * ```
 */
export function createAWSTranscribeSessionFactory(
  config: AWSTranscribeConfig = {}
): STTStreamingSessionFactory {
  const {
    websocketUrlEndpoint = '/api/voice-survey/stt/websocket',
    language: defaultLanguage = 'en-US',
    sampleRate: defaultSampleRate = 16000,
    initialTimeout = 5000,  // Short timeout for first attempt - fail fast, retry fast
    retryTimeout = 10000,   // Longer timeout for retries
    maxRetries = 3,
    finalTranscriptDelay = 1500,  // Wait 1.5s after final transcript before submitting
    debug = false,
  } = config;

  const log = debug ? console.log.bind(console, '[AWSTranscribeFactory]') : () => {};

  // Shared URL cache across sessions (URLs are valid for ~5 minutes)
  let cachedUrl: CachedUrl | null = null;
  let fetchPromise: Promise<CachedUrl> | null = null;

  /**
   * Invalidate the cached URL (used after connection failures)
   */
  function invalidateCache() {
    log('Invalidating URL cache');
    cachedUrl = null;
    fetchPromise = null;
  }

  /**
   * Fetch a new WebSocket URL (with deduplication)
   */
  async function fetchWebSocketUrl(language: string, sampleRate: number, forceRefresh = false): Promise<string> {
    // Force refresh invalidates cache
    if (forceRefresh) {
      invalidateCache();
    }

    // Check if cached URL is still valid (with 30 second buffer)
    if (cachedUrl) {
      const elapsed = (Date.now() - cachedUrl.fetchedAt) / 1000;
      if (elapsed < cachedUrl.expiresIn - 30) {
        log('Using cached URL (age:', Math.round(elapsed), 's)');
        return cachedUrl.url;
      }
      log('Cached URL expired');
      cachedUrl = null;
    }

    // If already fetching, wait for that request
    if (fetchPromise) {
      log('Waiting for existing fetch request');
      const result = await fetchPromise;
      return result.url;
    }

    // Fetch new URL
    log('Fetching new WebSocket URL');
    fetchPromise = (async () => {
      const params = new URLSearchParams({
        language,
        sampleRate: sampleRate.toString(),
      });

      const response = await fetch(`${websocketUrlEndpoint}?${params}`);
      const data = await response.json();

      if (!data.success || !data.websocketUrl) {
        throw new Error(data.error || 'Failed to get WebSocket URL');
      }

      const cached: CachedUrl = {
        url: data.websocketUrl,
        fetchedAt: Date.now(),
        expiresIn: data.expiresIn || 300,
      };

      cachedUrl = cached;
      fetchPromise = null;

      log('Got new WebSocket URL (expires in:', cached.expiresIn, 's)');
      return cached;
    })();

    const result = await fetchPromise;
    return result.url;
  }

  /**
   * Sleep for a given duration
   */
  function sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  return (
    onTranscript: (transcript: string, isFinal: boolean) => void,
    onError?: (error: string) => void,
    sessionConfig?: { language?: string; sampleRate?: number }
  ): STTStreamingSessionWithPrewarm => {
    const language = sessionConfig?.language || defaultLanguage;
    const sampleRate = sessionConfig?.sampleRate || defaultSampleRate;

    let innerSession: STTStreamingSessionWithPrewarm | null = null;
    let isConnecting = false;

    /**
     * Create a new session with retries
     */
    async function createNewSession(): Promise<STTStreamingSessionWithPrewarm> {
      let lastError: Error | null = null;

      for (let attempt = 1; attempt <= maxRetries; attempt++) {
        try {
          const timeout = attempt === 1 ? initialTimeout : retryTimeout;
          log(`Connection attempt ${attempt}/${maxRetries} (timeout: ${timeout}ms)`);

          // Always get fresh URL when creating new session
          const forceRefresh = attempt > 1 || innerSession !== null;
          const websocketUrl = await fetchWebSocketUrl(language, sampleRate, forceRefresh);

          const newSession = createAWSTranscribeSession(
            websocketUrl,
            onTranscript,
            onError,
            { connectionTimeout: timeout, finalTranscriptDelay, debug }
          );

          // Connect but start in paused state
          await newSession.preconnect();
          log('Connected successfully');
          return newSession;

        } catch (error) {
          lastError = error instanceof Error ? error : new Error(String(error));
          log(`Attempt ${attempt} failed:`, lastError.message);
          invalidateCache();

          if (attempt < maxRetries) {
            const delay = Math.min(500 * Math.pow(2, attempt - 1), 5000);
            log(`Retrying in ${delay}ms...`);
            await sleep(delay);
          }
        }
      }

      const errorMsg = lastError?.message || 'Failed to connect STT session';
      console.error('STT session connect failed after', maxRetries, 'attempts:', errorMsg);
      throw lastError;
    }

    /**
     * Ensure we have a connected session, creating/reconnecting if needed
     */
    async function ensureSession(): Promise<STTStreamingSessionWithPrewarm> {
      // If we have a connected session, reuse it
      if (innerSession?.isConnected) {
        log('Reusing existing connected session');
        return innerSession;
      }

      log('Session not connected, need to create/reconnect');

      // Avoid concurrent connection attempts
      if (isConnecting) {
        log('Connection already in progress, waiting...');
        // Wait for the ongoing connection attempt
        let waitCount = 0;
        while (isConnecting && waitCount < 100) {
          await sleep(100);
          waitCount++;
        }
        if (innerSession?.isConnected) {
          return innerSession;
        }
        // If still connecting after 10 seconds, something is wrong - proceed anyway
        if (isConnecting) {
          log('Connection wait timeout, proceeding with new connection');
          isConnecting = false;
        }
      }

      isConnecting = true;

      try {
        // Clean up old disconnected session
        if (innerSession) {
          log('Cleaning up previous session...');
          await innerSession.end().catch(() => {});
          innerSession = null;
        }

        // Invalidate URL cache to get a fresh URL
        invalidateCache();

        innerSession = await createNewSession();
        return innerSession;
      } finally {
        isConnecting = false;
      }
    }

    const session: STTStreamingSessionWithPrewarm = {
      get isActive() {
        return innerSession?.isActive ?? false;
      },

      get isConnected() {
        return innerSession?.isConnected ?? false;
      },

      get isPaused() {
        return innerSession?.isPaused ?? true;
      },

      /**
       * Pre-warm by fetching the WebSocket URL early.
       */
      async prewarm() {
        try {
          await fetchWebSocketUrl(language, sampleRate);
        } catch (error) {
          console.warn('STT prewarm failed (will retry on connect):', error);
        }
      },

      /**
       * Pre-connect the WebSocket. Call this during AI speaking
       * so the connection is ready when user needs to speak.
       * This is non-blocking and won't throw errors.
       * Note: If AI speaks for >15s, AWS may timeout this connection - that's OK,
       * we'll reconnect when user actually starts speaking.
       */
      async preconnect() {
        // Don't preconnect if already connected
        if (innerSession?.isConnected) {
          log('Already connected, skipping preconnect');
          return;
        }

        log('Pre-connecting...');
        try {
          await ensureSession();
          log('Pre-connect successful, connection ready');
        } catch (error) {
          // Pre-connect failures are non-fatal - will retry on start()
          log('Pre-connect failed (will retry on start):', error);
          // Make sure innerSession is null so start() will create fresh
          if (innerSession && !innerSession.isConnected) {
            innerSession = null;
          }
        }
      },

      /**
       * Start listening (resumes if paused, reconnects if disconnected)
       */
      async start() {
        log('Starting listening, isConnected:', innerSession?.isConnected);

        // Ensure we have a connected session
        const sess = await ensureSession();

        // Double-check connection after ensureSession
        if (!sess.isConnected) {
          log('Session not connected after ensureSession, retrying...');
          // Force cleanup and retry
          innerSession = null;
          const newSess = await ensureSession();
          if (!newSess.isConnected) {
            throw new Error('Failed to establish connection');
          }
          newSess.resume();
          return;
        }

        if (sess.isPaused) {
          log('Resuming paused session');
          sess.resume();
        } else if (!sess.isActive) {
          log('Starting fresh session');
          await sess.start();
        } else {
          log('Session already active');
        }
      },

      /**
       * Pause listening but keep connection open
       */
      pause() {
        innerSession?.pause();
      },

      /**
       * Resume listening after pause
       */
      resume() {
        innerSession?.resume();
      },

      sendAudio(audio: ArrayBuffer) {
        // Only send if connected
        if (innerSession?.isConnected) {
          innerSession.sendAudio(audio);
        }
      },

      /**
       * End the session and close the connection.
       * Call this only when the survey is complete.
       */
      async end() {
        if (innerSession) {
          await innerSession.end();
          innerSession = null;
        }
      },
    };

    return session;
  };
}

export type { AWSTranscribeConfig, STTStreamingSession, STTStreamingSessionFactory, STTStreamingSessionWithPrewarm };
